version: "3.11"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_NAME=base      
      - DB_USER=user
      - DB_PASSWORD=password
    restart: always
    ports:
      - "5432:5432"
  web:
    build: .
    volumes:
      - .:/app
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_PREFIX=/api
      - DB_HOST=localhost
      - DB_NAME=base
      - DB_USER=user
      - DB_PASSWORD=password
    command: /bin/sh -c "python3 app/main.py"
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
